### ISSUE TITLE
meta indexing

### ISSUE THREAD

**Issue by text2sql** [mayooear/gpt4-pdf-chatbot-langchain#104]
@mayooear how do you enable not sure how to call it, meta indexing? when chatbot understands which document is which and can compare between them, the one you made in the video about tsla 2020 vs 2021 or smth like that 
thank you!

**Comment by jagobagascon** [comment]
I'm having a similar problem. I'm ingesting several files and when I ask a question that involves data from several (or all) files then the chat bot is not capable of giving a good answer. 

> **Warning** I still don't fully understand how langchain works, so I may say something that is not correct.

**Let me know if I'm mistaken, but this is what I think it's happening**: first we use the given question to find the relevant document pieces in the vector store, then we use that as context to send the question to the OpenAI api. If the question is too vague, or if it involves lot's of documents, then the given context is not enough for the chatbot to respond.

My case involves several documents with information about some government subsidies. If I ask the chatbot to list all the available subsidies then it just gives me a couple of them or tells me that the given context is not enough.

**I think** that the 2020 vs 2021 comparison works fine because the answer it is part of the input PDF document:
![Screenshot 2023-04-05 at 18 31 33](https://user-images.githubusercontent.com/12712433/230145213-b361ec03-e81d-4804-b123-91ca2bfb006d.png)
