### ISSUE TITLE
Memory?

### ISSUE THREAD

**Issue by gorilla-san** [mayooear/gpt4-pdf-chatbot-langchain#113]
First of all, this is fantastic! Got it working in like 15 mins. Pretty cool stuff. 

But for some reason the bot doesn't remember previous back-and-forths. 

Is memory buffer implemented or does it not have it? 

I'll try figuring that out myself, too (I tried in like 10 minutes, but gotta go sleep now and it's gonna take me hours to figure it out as I'm a newbie), but thought it'd save me some time if somebody tells me if it's even implemented or not :-)

Thank you!

**Comment by stefansms** [comment]
I believe I am experiencing the same problem. The model behaves well in the first question. However, in subsequent questions it gets stuck with the sources from the first question.   

Even if the second question is from the same document, but on another subject, it cannot follow the conversation. 

Does anyone else have this same problem?

**Comment by danukito899** [comment]
Sane here, please help

**Comment by CharleoY** [comment]
This is because when the length grows, the model will decrease the attention to the contextual information. 
You can try in the chatGPT's web UI and use the max length it supports. You can see by after 2 questions it will forget the previous information since the length of input reaches the limitation. 
Similar here, how can the model remember the information in the previous conversation? Because each of your input is like an array that contains the history message and self-append with the new message.

**Comment by stefansms** [comment]
I don't know if it is possible. But maybe we could  use chatgpt to summarize the context to append in next question, keeping conversation flowing for at least 2 or 3 questions?
