### ISSUE TITLE
Failed to ingest your data

### ISSUE THREAD

**Issue by suomeimei** [mayooear/gpt4-pdf-chatbot-langchain#134]
![image](https://user-images.githubusercontent.com/32635006/229987182-04e70e53-e3fe-48bd-8165-6528f855c74e.png)

How can I solve this problem?

Where should I modify the code to make network requests in  proxy ? 

Thank you.

**Comment by bahram-ghahari** [comment]
I encountered the same problem when I attempted to take in `.json` data. It seemed that it was using two backslashes to avoid double quotes instead of one, which was causing the payload to be corrupted.

put a `JSON.stringify(error.response.data)` in your catch block to see what is the actual error.

In my case I ended up bypassing langchain and use openais embedding api directly.
