### ISSUE TITLE
Summarising documents

### ISSUE THREAD

**Issue by slpn1** [mayooear/gpt4-pdf-chatbot-langchain#139]
Hi. This is really good. Thank you very much.

It's probably my lack of understanding about how OpenAI queries the PineCone vectors but when I ask 'Please summarise this document' if I've just ingested a single document I receive the response:

 'The given context only includes a small excerpt from a longer document and does not provide enough information to summarise the entire document.'

All the documents I've ingested have been a dozen or so pages long. I can ask questions about specific things from the docs fine.

Is there a way I can get the summarisation ability to work with this?

Thanks,
Simon

**Comment by misteramazingyt** [comment]
I would like to second this with a more general question: how can we adjust the size of given context _in general_, for summarization or for any other purpose? If this is not possible given GPT's token limits, how can we _at least_ modify the code so that several tokens are read in tandem _effectively_ expanding the context? Thank you!
