### ISSUE TITLE
How to improve answer generation to include insights from all provided sources?

### ISSUE THREAD

**Issue by riceorpasta** [mayooear/gpt4-pdf-chatbot-langchain#153]
First, awesome job on this and thank you for making it public!

Currently, when generating answers, the chatbot only incorporates insights from 2-3 sources in its response, even though 10+ relevant sources are available. My dataset is made of 100+ pdfs of a relative short length (5-10 pages). I'm not advanced enough to figure it out but it seems there is some bias that may cause the model to focus on a few highly-weighted sources? How can we solve that?

I've experimented with different max_tokens, temperatures and prompts but i can't overcome the issue.  Thanks again for the help/direction

**Comment by Nissou31** [comment]
I have the same issue

**Comment by awilliamson** [comment]
@riceorpasta If the volume of tokens is going to be an issue, an approach could be to pre-process documents into brief summaries once. Then use a collection of the summaries to produce a reduced amount of tokens for a wider-reaching context. Then if you did want to drill down on specific sources, you can go back to the normal full-resolution embeddings per document.

At least, that's the first thought that popped into my head for this.

**Comment by disturbed-mystic1** [comment]
Any fix for this??

**Comment by bschleter** [comment]
@vishnu1991 Had the best insights on this. 

@riceorpasta I have a similar setup where I have my own data generated into documents about 2-10 pages in length. I did k=3 as 3 sources was enough for my use case but I understand how you'd like to take all relevant sources. 

Two-three possible solutions/experiments you could do immediately:
- I think the cheapest albeit low tech way is to reorganize your datasets into docs of all relevancy into fewer docs. 
- Another thing you could possibly also do is increase the chunk size to 2,000, which is the limit Pinecone allows you to do. Be prepared to maybe run into issues though as pinecone seems somewhat finicky as we are very early in this game, especially on lower compute free nodes. I would increase chunk size after combining similar docs into fewer to help. 
- There are other experiments like trying another chunk embedding algo like FAISS, or after formatting docs doing a segmentation chunker based on spacing in docs,but I don't think that solves your issue here. 
- Maybe just maybe, it's the issue in parsing of your PDFs depending on how they are formatted if not simple straight text and have other elements. I added a basic text loader into my tryouts, as I barely had any PDFs, I had just raw text. I did notice once though, even in my raw text that my 1st source and third source were same document. I don't have much money to experiment. 

These models tend to just return the highest confidence scores, and if you have 3 of high confidence ~81%, then your 4th and 5th document of confidence of ~75% just won't return as a source. You likely already know this.

**Comment by RazeBerry** [comment]
@bschleter Thanks for the response! Was wondering where can I find the file where I can increase the chunk size specification? In addition, I realize the output by GPT-4 API form is very concise, was wondering if you know how to modify it and where to modify so it produces more verbose output?

**Comment by simon555** [comment]
Hi @bschleter ! Where in the code can you increase the number of sources to retrieve ?

Thanks!
