### ISSUE TITLE
Failed to ingest data - invalid PDF exception

### ISSUE THREAD

**Issue by umanglani** [mayooear/gpt4-pdf-chatbot-langchain#162]
I am getting an error while trying to ingest PDFs which are provided in the repo. I have setup openai and pinecode API keys and index name etc.

error [InvalidPDFException: Invalid PDF structure]
...\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:45
    throw new Error('Failed to ingest your data');

**Comment by DialloYoussouf** [comment]
Try this with your error_message https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/157#issuecomment-1506578204

**Comment by umanglani** [comment]
> Try this with your error_message [#157 (comment)](https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/157#issuecomment-1506578204)

sorry I didn't follow. The error is different and I can't ask chatgpt, office computer. Using node 18 by the way.

**Comment by mayooear** [comment]
Try a different PDF to see if it's an issue with a corrupted pdf.

**Comment by bschleter** [comment]
Unfortunately try with a different pdf. I got similar errors with _ds.store errors and was rather difficult to figure out which one it was. 

I've done this repo couple times over now, and I've come to find PDFs from certain public places/old/lot of images will possibly lead to failure as pdf parser is unable to parse through. 

The issue is likely your pdf. See if there is an outside way to convert your pdf to text, then try. You'll need to add a text loader to the code. 
If you don't want to do that, a workaround is convert pdf to text, then save that txt file back to pdf without the original elements. It'll be crude, but it'll at least get it working until you can figure out the real problem.
