### ISSUE TITLE
Generate summary tables for my usecase

### ISSUE THREAD

**Issue by disturbed-mystic1** [mayooear/gpt4-pdf-chatbot-langchain#173]
I want to generate summary tables for my use case; however, it seems Gpt 3.5 can't do that (not sure if some clever prompt engineering would work), and I don't yet have access to GPT 4. Is there some workaround to generate this using GPT3?

**Comment by bschleter** [comment]
What has your prompt template looked like? Also, the QA template before it doesn't really provoke a response to return a table format, mostly text.

**Comment by disturbed-mystic1** [comment]
`You are an AI assistant providing answers to questions based on diabetics clinical trials. You are given the following extracted parts of a long document and a question. Provide a conversational answer based on the context provided.
You should only provide hyperlinks that reference the context below. Do NOT make up hyperlinks. Also, provide a page number for the article in which the answer lies. Also, Provide more sources if requested. Also, if asked to provide a table, please create a .csv table.
If you can't find the answer in the context below, just say "Hmm, I'm not sure." Don't try to make up an answer.
If the question is not related to the context, politely respond that you are tuned to only answer questions that are related to the context.

Question: {question}
=========
{context}
=========
Answer in Markdown:`,
);

This was the prompt

**Comment by disturbed-mystic1** [comment]
Oh, but I thought ChatGPT is able to generate tables??

**Comment by bschleter** [comment]
it can. 

I wanted to see prompt template because I'm speculating it's the prompt template, especially if you are using gpt 3.5 instead of 4 as attention towards whole prompt not as good as 4.

I wanted to check in the condense_prompt which you could change up possibly to maybe help, but mostly your QA prompt. Try removing or adjusting the bold text in your QA prompt below:

"You are an AI assistant providing answers to questions based on diabetics clinical trials. You are given the following extracted parts of a long document and a question. **Provide a conversational answer** based on the context provided.

You should only provide hyperlinks that reference the context below. Do NOT make up hyperlinks. Also, provide a page number for the article in which the answer lies. Also, Provide more sources if requested. Also, if asked to provide a table, please create a **.csv** table."

You may want to just say a table, or maybe an ASCII table. The format of the table may be tough in this basic instance as can't put an actual csv in the UI box or trouble formatting an actual file and allow you to view it. Try to get a table first. 

I would venture to guess 3.5 turbo is putting just a bit more weight towards 'conversational answer' since it is mostly a QA bot, and the accuracy weighting towards the "make a table if asked to provide a table" isn't high enough, so it simply doesn't. 

May need to do a few more things, such as the UI not allowing a table based answer due to height, format, other things, or may need additional langchain tools to make work. But the easiest thing is try removing the bold first and then check. Speculating.

**Comment by disturbed-mystic1** [comment]
I will try it out! Thanks for the help!
