### ISSUE TITLE
getting error "Error: Missing Pinecone index name in .env file"

### ISSUE THREAD

**Issue by Aevark02** [mayooear/gpt4-pdf-chatbot-langchain#209]
I get this error no matter what i do when i try to run the ingest despite having the index name defined in the .env. Any suggestions?

**Comment by JosephKrebs** [comment]
Make sure you are using the name you assigned the index, rather than the ID Pinecone assigns it.

For example, in the below example, you should use my-nama-jeff rather than my-nama-jeff-*****.svc.asia-southeast1-gcp.pinecone.io

![image](https://user-images.githubusercontent.com/58876030/234490366-1fc49ca3-306e-463d-9398-944a22cb134f.png)
