### ISSUE TITLE
"ConversationalRetrievalQAChain is not defined"

### ISSUE THREAD

**Issue by 2334347153** [mayooear/gpt4-pdf-chatbot-langchain#251]
After running npm run dev successfully, I went to http://localhost:3000/ and tried to input some question, this is what showed on the page "ConversationalRetrievalQAChain is not defined" and no answer has returned from the bot. I am sure that I have gpt-4 available for my account. Does anyone else has this problem?
error ReferenceError: ConversationalRetrievalQAChain is not defined

**Comment by akashchaudhary-git** [comment]
While querying the chat bot it throws `error - [Error: Invalid _type: undefined] { page: '/api/chat' }`
I don't know the root cause yet but it shows the `ChatVectorDBQAChain` is deprecated and we need to use  `ConversationalRetrievalQAChain` instead.

PS - I'm trying to integrate with `AzureOpenAI` I successfully tried to ingest data but I cant get response from the chat bot because of above error

**Comment by ahm750** [comment]
Having same issue

**Comment by penguinff** [comment]
run `npm update langchain`, I updated langchain to version ^0.0.76 and the problem solved.

**Comment by Arham-12336** [comment]
having same issue.Even after updating the langchainjs.
