### ISSUE TITLE
Pinecone error

### ISSUE THREAD

**Issue by rileydev** [mayooear/gpt4-pdf-chatbot-langchain#40]
I keep getting this error: 

error [Error: PineconeClient: Error calling query: Error: PineconeClient: Error calling queryRaw: FetchError: The request failed and the interceptors did not return an alternative response]

when i try to ask a question... ingestion also doesn't work... 

I've double checked my env settings as well as pinecone config.  

any idea what this could be?

**Comment by rawsh** [comment]
https://github.com/hwchase17/langchainjs/pull/413

**Comment by IvanVeridian** [comment]
I got a similar error and it's because I didn't define the index name. 
More info from mayo:
Hey there are several potential culprits behind this. I cover them https://github.com/mayooear/gpt4-pdf-chatbot-langchain/discussions/6 in the discussions section.

Here are potential causes of the error, I posted below. Try them out and let me know if you still encounter issues.

Troubleshoot the following:

In the config folder, replace the PINECONE_INDEX_NAME to match your index name in pinecone.

Upgrade your node version to the latest. It's possible you're using a version of Node that doesn't support fetch natively.

Make sure to set Dimensions in the Pinecone dashboard to 1536. (These are OpenAI embeddings dimensions).

Switch your Environment in pinecone to us-east1-gcp if the other environment is causing issues.

Ensure you have a .env file in the root that contains valid API keys from the pinecone dashboard.

Pinecone has limits for each upsert operation, you can read them [here](https://docs.pinecone.io/docs/limits#:~:text=Max%20size%20for%20an%20upsert,to%20queries%20immediately%20after%20upserting.) and see some below. If you are uploading massive PDF files, you just need to write a loop to ensure upserts don't exceed 100 chunks per request. I will make a PR to the LangChain repo to integrate this.

Max size for an upsert request is 2MB. Recommended upsert limit is 100 vectors per request.
Max metadata size per vector is 40 KB.
Pinecone indexes of users on the Starter(free) plan are deleted after 7 days of inactivity. To prevent this, send an API request to Pinecone to reset the counter.

https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/4

**Comment by MakkiAi** [comment]
did you manage to make that PR, for the 100 chunks per request, I applied all troubleshooting and I still get the same pinecone error 

error [Error: PineconeClient: Error calling query: Error: PineconeClient: Error calling queryRaw: FetchError: The request failed and the interceptors did not return an alternative response]

**Comment by mayooear** [comment]
PR is complete, but **do not upgrade langchain or pinecone versions above the current repo as there are breaking changes.** I have already added a custom chunking function to this repo so you shouldn't face those errors.

**Comment by varunp789** [comment]
how can we if find query answer using namespace
