### ISSUE TITLE
Issue reading PDFS

### ISSUE THREAD

**Issue by focusai** [mayooear/gpt4-pdf-chatbot-langchain#88]
Just to highlight that some PDFs just don't read during the ingest process. So if you think it's not working it could actually be the PDF. Possibly just the OCR during the process? Does anyone know of a solution to this? Or what would cause certain PDF files to be unreadable?

Thanks

**Comment by bschleter** [comment]
i had this issue too, they wouldn't even ingest. I got a .ds_store error, so delete a few pdfs that aren't necessarily viewable, and this allowed me to ingest and solve the issue. There might be an issue with PDF reader etc. I think this initial repo worked well because the PDFs were so simple, mostly text but I think the PDF reader struggles with PDFs with images and other elements.

**Comment by focusai** [comment]
Makes sense, thanks for sharing

**Comment by mayooear** [comment]
Yes, good point. OCR, corrupted/non-viewable PDFs and scanned PDFs are very difficult to read, so that is another cause of errors.
